### ISSUE TITLE
lru-cache: typeError

### ISSUE THREAD

**Issue by JoseP-UR** [originjs/vue-sfc-ast-parser#1]
there is a typeError when executing the webpack-to-vite script and it's realted to this project not properly instantiating lru-cache by passing it's max size inside the options object
the problem is located at /src/sfcUtils.ts:162

Currently it looks like this:

`(require('lru-cache'))(SFC_CACHE_MAX_SIZE)`

It needs to be like this

`(require('lru-cache'))({ max: SFC_CACHE_MAX_SIZE })`

**Comment by PeterAlfredLee** [comment]
Hi @JoseP-UR 
Thanks for your reporting.

@mrhammadasif has pushed a fix and I have merged it. Seems this has been fixed. I will make a new release soon.
Feel free to reopen this issue if there's something new.
